name: CI/CD Frontend Innovatech

on:
  push:
    branches: [ "deploy" ]
    paths:
      - "front_despacho/**" # CORREGIDO: Apunta a tu carpeta real

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Solo si usas AWS Academy
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y Subir Imagen Docker (Build & Push)
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: innovatech-frontend
        IMAGE_TAG: latest
      run: |
        # CORREGIDO: Entramos a la carpeta real del frontend
        cd front_despacho
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Despliegue en Instancia EC2 Frontend (CD)
      uses: appleboy/ssh-action@v1.0.3
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: innovatech-frontend
        IMAGE_TAG: latest
      with:
        host: ${{ secrets.EC2_FRONTEND_HOST }} # IP Pública del Front
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: ECR_REGISTRY, ECR_REPOSITORY, IMAGE_TAG
        script: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
          
          # Detener y eliminar contenedor viejo
          docker stop frontend-app || true
          docker rm frontend-app || true
          
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Levantar el Front exponiendo el puerto 80
          docker run -d --name frontend-app \
            --restart always \
            -p 80:80 \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG