name: Deploy Infraestructura AWS Innovatech

on:
  workflow_dispatch:
  push:
    branches: [ "main", "deploy" ]
    paths:
      - "scripts/**"

jobs:
  build-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Solo si usas AWS Academy
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Ejecutar script de AWS CLI
      run: |
        chmod +x ./scripts/crear-infra-innovatech.sh
        ./scripts/crear-infra-innovatech.sh